const $=id=>document.getElementById(id);const v=$('cameraVideo'),ov=$('overlayImage'),vp=$('cameraViewport');let stream=null,devices=[],front=null,back=null;
$('referenceInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=x=>{$('referencePreview').innerHTML=`<img src="${x.target.result}">`;ov.src=x.target.result;ov.style.display='block'};r.readAsDataURL(f)};
$('opacitySlider').oninput=e=>{$('opacityValue').textContent=e.target.value+'%';ov.style.opacity=Number(e.target.value)/100};
function scale(z){$('zoomValue').textContent=Number(z).toFixed(2)+'×';vp.style.setProperty('--camera-scale',z);document.querySelectorAll('.preset-btn').forEach(b=>b.classList.toggle('active',Number(b.dataset.zoom)===Number(z)))}$('zoomSlider').oninput=e=>scale(e.target.value);document.querySelectorAll('.preset-btn').forEach(b=>b.onclick=()=>{$('zoomSlider').value=b.dataset.zoom;scale(b.dataset.zoom)});
function stop(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;v.srcObject=null}
async function init(){stop();const temp=await navigator.mediaDevices.getUserMedia({video:true,audio:false});temp.getTracks().forEach(t=>t.stop());devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='videoinput');front=devices.find(d=>/front|user|facetime/i.test(d.label))||devices[0];back=devices.find(d=>/back|rear|environment|wide/i.test(d.label))||devices.at(-1);$('frontCameraBtn').disabled=!front;$('backCameraBtn').disabled=!back;if(back)open(back,'후면');else if(front)open(front,'전면')}
async function open(d,label){stop();try{stream=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:d.deviceId}},audio:false});v.srcObject=stream;await v.play();v.style.display='block';$('cameraPlaceholder').style.display='none';$('captureBtn').disabled=false;$('cameraStatus').textContent=label+' LIVE';$('cameraMessage').textContent=label+' 카메라 연결 완료'}catch(e){$('cameraMessage').textContent=label+' 카메라 연결 실패: '+e.name}}
$('startCameraBtn').onclick=init;$('frontCameraBtn').onclick=()=>open(front,'전면');$('backCameraBtn').onclick=()=>open(back,'후면');
$('captureBtn').onclick=()=>{const c=$('captureCanvas'),ctx=c.getContext('2d');c.width=v.videoWidth;c.height=v.videoHeight;ctx.drawImage(v,0,0,c.width,c.height);$('capturePreview').innerHTML=`<img src="${c.toDataURL('image/jpeg',.9)}">`};scale(1);
